[package]
name = "rusty_ssg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.47", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
pulldown-cmark = "0.13"
tera = "1.20"
walkdir = "2.5"
